# Generated by Django 3.1 on 2020-09-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_name', models.CharField(max_length=200)),
                ('playtime', models.IntegerField()),
                ('money_spent', models.IntegerField()),
            ],
        ),
    ]
